export const CREATE_USER_REQUEST = 'CREATE USER REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE USER SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE USER FAILURE'

export const UPDATE_USER_REQUEST = 'UPDATE USER REQUEST'
export const UPDATE_USER_SUCCESS = 'UPDATE USER SUCCESS'
export const UPDATE_USER_FAILURE = 'UPDATE USER FAILURE'
